Template.disqus.rendered = function() {

  /*
   * We don't want to load Disqus until the first time the template is
   * rendered, since it requires the #disqus_thread div
   * Triggers Deps.autorun (below)
   */
  var disqusSignon;
  Session.set("loadDisqus", true);

  /*
   * OPTIONAL: Only include the part below if you're using
   * Disqus single-sign on
   * Generate the disqusSignon variable appropriately from your server
   */
  disqusSignon = Session.get("disqusSignon");
  if (Meteor.user() && disqusSignon) {
    window.disqus_config = function() {
      this.page.remote_auth_s3 = "" + disqusSignon.auth;
      return this.page.api_key = "" + disqusSignon.pubKey;
    };

    /*
     * Whenever the template is rendered, trigger a Disqus reset.
     * This will find the correct thread for the current page URL.
     * See http://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites
     */
    return typeof DISQUS !== "undefined" && DISQUS !== null ? DISQUS.reset({
      reload: true,
      config: function() {}
    }) : void 0;
  }
};

Deps.autorun(function() {
  if (Session.get("loadDisqus") && !window.DISQUS) {
    return
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'YOUR_SHORTNAME'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
     })();
     ;
  }
});

// ---
// generated by coffee-script 1.9.0
